name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build ðŸ”§
        run: |
          npm install
        # npm run lint:js
        #  npm run build

      #- name: Deploy ðŸš€
      #  uses: JamesIves/github-pages-deploy-action@4.1.0
      #  with:
      #    branch: gh-pages
      #    folder: build

      # - run: set -eu
      # - run: mkdir "$HOME/.ssh"
      # - run: echo "${{ secrets.mymcicu }}" > "$HOME/.ssh/key"
      # - run: chmod 600 "$HOME/.ssh/key"
      # #Deploy
      # - run:
      #     rsync -e "ssh -p 22 -i $HOME/.ssh/key -o
      #     StrictHostKeyChecking=no"  --archive --compress --delete  --exclude
      #     '.github' --exclude '.git' .
      #     mymcicu@mymc.icu:/home/mymcicu/repositories/project-nodejs_55-5_backend
